import antigravity

CERT="""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACC4zDO1C3SsH5ZZPhS/zHBHa24kGOVpFFdpMLNNh7dhGwAAAJC+2VcZvtlX
GQAAAAtzc2gtZWQyNTUxOQAAACC4zDO1C3SsH5ZZPhS/zHBHa24kGOVpFFdpMLNNh7dhGw
AAAEBsaLUzm3/BaOdg6eJBk1Uy8eN8LGoPmESBLXrcJJMJL7jMM7ULdKwfllk+FL/McEdr
biQY5WkUV2kws02Ht2EbAAAABm15LWtleQECAwQFBgc=
-----END OPENSSH PRIVATE KEY-----
"""

def main():
    antigravity.fly()

if __name__ == "__main__":
    main()
